export const mockSystem = {
  CURRENCY: "EUR",
  POINTS_EXPIRATION_DAYS: 180,
  EARNED_POINTS_X_UNIT: 100,
  POINTS_UNIT_VALUE_CENTS: 100,
  MEMBER_LEVELS: [
    { id: "BRONZE", pointsRequired: 0, discount: 5 },
    { id: "SILVER", pointsRequired: 5000, discount: 10 },
    { id: "GOLD", pointsRequired: 10000, discount: 15 },
  ],
  REWARDS: [
    {
      id: "beer-or-taco",
      title: "CHELA O TACO GRATIS",
      description: "Tienes un taco o chela gratis en tu siguiente compra.",
      pointsRequired: 3000,
      type: "recurrent",
      expiryDate: "2026-01-01T03:00:00.000Z",
      expirationDays: 30,
      status: "ACTIVE",
      image: "https://picsum.photos/seed/coffee/300/200",
    },
    {
      id: "nachos-half-order",
      title: "MEDIA DE NACHOS GRATIS",
      description: "Llévate media orden de nachos gratis.",
      pointsRequired: 9000,
      type: "once",
      expiryDate: "2026-01-01T03:00:00.000Z",
      expirationDays: 30,
      status: "ACTIVE",
      image: "https://picsum.photos/seed/coffee/300/200",
    },
    {
      id: "free-jarra",
      title: "JARRA GRATIS",
      description: "Obtén una jarra de cerveza gratis.",
      pointsRequired: 7000,
      type: "once",
      expiryDate: "2026-01-01T03:00:00.000Z",
      expirationDays: 30,
      status: "ACTIVE",
      image: "https://picsum.photos/seed/coffee/300/200",
    },
  ],
};
